import = ["~/AppData/Roaming/alacritty/carbonfox-colors.toml"]

[shell]
program = "C:\\cygwin64\\bin\\bash.exe"
args = ["-li"]

[window]
opacity = 0.90
startup_mode = "Maximized"

[selection]
save_to_clipboard = true

[cursor]
style = { blinking = "On" }

[font.normal]
family="IntoneMono Nerd Font"
