import = ["~/AppData/Roaming/alacritty/carbonfox-colors.toml"]

[shell]
program = "ubuntu"

[window]
opacity = 0.90
startup_mode = "Maximized"

[selection]
save_to_clipboard = true

[cursor]
style = { shape = "Underline", blinking = "Off" }
thickness = 0.5

[font.normal]
family="IntoneMono Nerd Font"
